### ISSUE TITLE
Route uuid binding Laravel 8

### ISSUE THREAD

**Issue by joshwegener** [michaeldyrynda/laravel-model-uuid#104]
(Please note I 'm not to UUIDs) I'm using Laravel with Jetstream, I'm trying to add the scope binding for URL routes, but I get an error with \App\Post, has this moved in laravel 8?

```
// app/Providers/RouteServiceProvider.php

Route::bind('post', function ($post) {
    return \App\Post::whereUuid($post)->first();
});
```

Thanks!

**Comment by joshwegener** [comment]
Oh I feel stupid... \App\Post is a model example....

**Comment by joshwegener** [comment]
I assume if I use explicit binding I won 't have this issue?

```
Route::model('user', User::class);
```

**Comment by michaeldyrynda** [comment]
I don't have enough context with your issue to comment either way. What error are you getting or what are you trying to achieve? How can I make the documentation clearer for your use case?

**Comment by RoobieBoobieee** [comment]
@joshwegener is referencing https://laravel.com/docs/8.x/routing#route-model-binding. 
```php
use App\Http\Controllers\UserController;
use App\Models\User;

// Route definition...
Route::get('/users/{user}', [UserController::class, 'show']);

// Controller method definition...
public function show(User $user)
{
    return view('user.profile', ['user' => $user]);
}
```
This will work with the route: `/users/1` where `1` is the id of the user model. But if you're using uuids in your route this won't work. 

One solution is to add the following in a service provider (obliviously out of the scope of the package): 
```php
Route::bind('user', function ($uuid) {
    return \App\Models\User::whereUuid($uuid)->firstOrFail();
});
``` 
You'll have to do this for every model that uses uuids in its routes which is too cumbersome imo. 

Another solution is to add on the model:
```php
    /**
     * Retrieve the model for a bound value.
     *
     * @param  mixed  $value
     * @param  null|string  $field
     *
     * @return null|\Illuminate\Database\Eloquent\Model
     */
    public function resolveRouteBinding($value, $field = null)
    {
        return $this->whereUuid($value, $field)->firstOrFail();
    }
```

This could be done on the `GeneratesUuid` trait in the package but then we would assume all models with the trait are using uuids in their routes. 

I suggest @joshwegener creates a parent model in their codebase with the `resolveRouteBinding` function.

**Comment by michaeldyrynda** [comment]
Can you not just override the [`getRouteKeyName`](https://github.com/michaeldyrynda/laravel-model-uuid#route-model-binding) method on the models that require implicit binding?
