### ISSUE TITLE
is it possible to generate uuid for existing db entry? 

### ISSUE THREAD

**Issue by Sjos12** [michaeldyrynda/laravel-model-uuid#111]
I have some users on my live server and only recently used this package to add a UUID to the user model. Is it possible to still generate a uuid for the users that were already registered before I added UUIDs to the site? Thanks!

**Comment by michaeldyrynda** [comment]
The package functionality will only generate a new UUID for a (new) model’s `creating` event. 

If you need to backfill existing records, you’d need to do so yourself either manually with tinker, via a one-time command, or inside of a database migration.
