### ISSUE TITLE
[7.1] Dev package requirement

### ISSUE THREAD

**Issue by TomKita** [michaeldyrynda/laravel-model-uuid#128]
Hi I'm getting the following error.

```
In LaravelModelUuidServiceProvider.php line 9: Class "Spatie\LaravelPackageTools\PackageServiceProvider" not found
```

The Spatie package is marked as a dev only in this project's composer.json.

**Comment by aswinghosh-2hats** [comment]
Same here

**Comment by michaeldyrynda** [comment]
[Fixed](https://github.com/michaeldyrynda/laravel-model-uuid/releases/tag/7.1.1) - sorry about that! 😅
