### ISSUE TITLE
UUID not generated for seeders

### ISSUE THREAD

**Issue by pvledoux** [michaeldyrynda/laravel-model-uuid#13]
The seeder run() method:

    public function run()
    {
        DB::table('users')->insert([
            'firstName' => 'Admin',
            'lastName' => 'Admin',
            'email' => 'admin@acme.com',
            'password' => app('hash')->make('secret'),
        ]);
    }

I have uuid field in my user table:

    // part of the migration
    $table->string('uuid', 36)->unique();

And the trait is in my Model:

    class User extends Model
    {
        use GeneratesUuid;

Any idea? Thanks!

**Comment by michaeldyrynda** [comment]
Hey!

Eloquent events won't fire in this case, as you're working with the query builder directly.

**Comment by pvledoux** [comment]
Damned, of course! You can burn this issue in the fire of my stupidity ;)

So Something like 'uuid' => \Ramsey\Uuid\Uuid::uuid4()->toString()

I presume... Cheers!

**Comment by michaeldyrynda** [comment]
Yep, that'll do the trick!
