### ISSUE TITLE
Laravel 11 compatibility

### ISSUE THREAD

**Issue by suhui666** [michaeldyrynda/laravel-model-uuid#131]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dyrynda/laravel-model-uuid[7.0.0, ..., 7.1.1] require illuminate/database ^10.0 -> found illuminate/database[v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-model-uuid[6.6.0, ..., 6.6.3] require illuminate/database ^8.12|^9.0 -> found illuminate/database[v8.12.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-model-uuid[6.4.0, ..., 6.5.0] require illuminate/database ^8.12 -> found illuminate/database[v8.12.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-model-uuid 6.3.0 requires php ^7.3 -> your php version (8.2.12) does not satisfy that requirement.
    - dyrynda/laravel-model-uuid[6.0.0, ..., 6.2.0] require php ^7.2.5 -> your php version (8.2.12) does not satisfy that requirement.
    - dyrynda/laravel-model-uuid 5.0.0 requires php ^7.2 -> your php version (8.2.12) does not satisfy that requirement.
    - dyrynda/laravel-model-uuid[4.1.0, ..., 4.1.1] require php ^7.1.3 -> your php version (8.2.12) does not satisfy that requirement.
    - dyrynda/laravel-model-uuid[4.0.0, ..., 4.0.1] require illuminate/database 5.6.* -> found illuminate/database[v5.6.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-model-uuid[3.1.0, ..., 3.1.1] require illuminate/database 5.3.* || 5.4.* || 5.5.* || 5.6.* -> found illuminate/database[v5.3.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-model-uuid 3.0.0 requires illuminate/database 5.3.* || 5.4.* || 5.5.* -> found illuminate/database[v5.3.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-model-uuid[1.0.0, ..., 1.0.1, 2.0.0, ..., 2.0.3] require illuminate/database 5.3.* || 5.4.* -> found illuminate/database[v5.3.0, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires dyrynda/laravel-model-uuid * -> satisfiable by dyrynda/laravel-model-uuid[1.0.0, 1.0.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.0.1, 4.1.0, 4.1.1, 5.0.0, 6.0.0, ..., 6.6.3, 7.0.0, 7.1.0, 7.1.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require dyrynda/laravel-model-uuid:*" to figure out if any version is installable, or "composer require dyrynda/laravel-model-uuid:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by drbyte** [comment]
It's possible that your `composer.lock` and/or your `/vendor` directory is blocking the upgrade because of other dependencies previously downloaded.

Sometimes `rm -rf vendor composer.lock` will allow you to do the `composer require` that was being rejected.

**Comment by drbyte** [comment]
Correct. Until a release is tagged, must use the 7.x-dev branch:
`composer require dyrynda/laravel-model-uuid:7.x-dev`

**Comment by suhui666** [comment]
> 正确的。在标记版本之前，必须使用 7.x-dev 分支： `composer require dyrynda/laravel-model-uuid:7.x-dev`

Thank you for your suggestion! However, I tried using the 7.x-dev branch method and found that it does not solve the issue encountered in Laravel 11. It seems that this problem requires a different solution. If you have any other suggestions or are aware of a specific solution that is suitable for Laravel 11, please share it with me. I greatly appreciate your help!

**Comment by drbyte** [comment]
I just tested it on PHP 8.2.16 using:

`laravel new laravel11` to install a fresh Laravel 11 project.
and then 
`cd laravel11`
`composer require dyrynda/laravel-model-uuid:7.x-dev`  to install this package.

Composer installed correctly without errors.

**Comment by suhui666** [comment]
> I just tested it on PHP 8.2.16 using:
> 
> `laravel new laravel11` to install a fresh Laravel 11 project. and then `cd laravel11` `composer require dyrynda/laravel-model-uuid:7.x-dev` to install this package.
> 
> Composer installed correctly without errors.


Okay, it works now, but please note that this isn't a stable version. We're using a development branch, so while the immediate issue is resolved, it's important to be cautious and monitor for any updates or releases that provide a stable solution. Thank you for pointing me in the right direction!

**Comment by drbyte** [comment]
Actually, probably should use: `8.0.0-beta.1`
`composer require dyrynda/laravel-model-uuid:8.0.0-beta.1`

(7.x-dev "works" because composer.json contains an alias for it, but they'll probably update that to 8.x-dev when 8.0 is officially released)
