### ISSUE TITLE
Strings with invalid UTF-8 byte sequences cannot be escaped.

### ISSUE THREAD

**Issue by masterix21** [michaeldyrynda/laravel-model-uuid#135]
| Package | Version | 
|-|-|
| php | 8.3.8 |
| laravel | 11.11.1 | 
| laravel-model-uuid | 8.0.0 |
| ramsey/uuid | 4.7.6 |
| mysql-server | 8.3.0 |

Hi.

Using your package, I'm facing the error `Strings with invalid UTF-8 byte sequences cannot be escaped.`.

I've added the column `uuid` to my users table like so:
```php
Schema::table('users', function (Blueprint $table) {
    $table->efficientUuid('uuid')->after('id')->unique();
});
```

Then, I've changed the `User` model like so:
```php
class User extends Authenticatable implements MustVerifyEmail, Subscriber
{
    // ... other traits ...
    use GeneratesUuid;

    // ...

    protected function casts(): array
    {
        return [
            'uuid' => EfficientUuid::class,
            'email_verified_at' => 'datetime',
        ];
    }
}
```

After all, I've created in the `web.php` an endpoint like this:
```php
Route::get('/test', function () {
    return response()->json(
        User::create([
            'first_name' => fake()->firstName(),
            'last_name' => fake()->lastName(),
            'email' => fake()->email,
            'mobile' => fake()->phoneNumber(),
            'password' => Hash::make('password'),
        ])
    );
});
```

Finally, the result with `/test` is:
<img width="1413" alt="image" src="https://github.com/michaeldyrynda/laravel-model-uuid/assets/6555012/5445b07d-8237-405f-9888-dcd56739ee22">

Do you happen to have an idea to solve this? 

Thanks!

**Comment by masterix21** [comment]
Found! The issue is caused by Telescope.

**Comment by pindab0ter** [comment]
> Found! The issue is caused by Telescope.

Did you find a solution other than not using Telescope?

**Comment by masterix21** [comment]
Analyzing the error stack
