### ISSUE TITLE
Route model binding and laravel-efficient-uuid package

### ISSUE THREAD

**Issue by softquantum** [michaeldyrynda/laravel-model-uuid#21]
My issue is [SOLVED] but will post here to reference the quick solution.  Sorry if it is not the place.  I am using laravel-efficient-uuid along with this package so you need to cast the value for uuid.

I want to use the uuid in my routes to retrieve a model instead of using the id. So I also override the function in the model as per Laravel doc.:
```
protected $casts = ['uuid' => 'uuid'];

public function getRouteKeyName()
 {
        return 'uuid';
 }
```
My query got back empty all the time since the query used by the implicit model binding is not using the scope defined by the Trait of this package.  The solution is to be explicit about the model binding.

```
// in RouteServiceProvider

Route::bind('whatever', function ($value) {
     return \App\YourModel::whereUuid($value, 'uuid')->first();
});
```

Hope it helps

**Comment by michaeldyrynda** [comment]
I've updated the readme; thanks @softquantum 👍

**Comment by kynetiv** [comment]
I'm using this approach too (thanks!), and noticed that if you pass in a random string that is not a uuid as your route parameter, I get a 500 error. Thought I'd share my workaround to avoid the exception.

> Ramsey \ Uuid \ Exception \ InvalidUuidStringException
Invalid UUID string: random-string

I remedied it by checking that the parameter is in fact a uuid with `isValid` (which seems to have been added around L5.6).

```php
     if (!\Ramsey\Uuid\Uuid::isValid($uuid) ) {
         return null;
     }
     Route::bind('whatever', function ($value) {
          return \App\YourModel::whereUuid($value, 'uuid')->first();
     });
```

**Comment by boranbar** [comment]
@kynetiv I got the same error. I fixed with Handler.php. I don't know is it the right way, but it works fine...
**App\Exceptions\Handler.php**;

```
use Ramsey\Uuid\Exception\InvalidUuidStringException;

public function render($request, Throwable $exception)
    {
        
        if ($exception instanceof InvalidUuidStringException) {
            abort(404);
        }
        
        return parent::render($request, $exception);
    }
```

**Comment by tylerssn** [comment]
> ```
>      if (!\Ramsey\Uuid\Uuid::isValid($uuid) ) {
>          return null;
>      }
> ```

@kynetiv - do you recall where you placed this? Was it literally before the `Route::bind`?

I'm getting the same 500 error when passing a non-uuid through the url param
