### ISSUE TITLE
Update to support Laravel 5.6

### ISSUE THREAD

**Issue by pushchris** [michaeldyrynda/laravel-model-uuid#38]
Currently the composer file for this package requires specified version numbers of Laravel. Can we please get the newly released Laravel 5.6 added in?

https://github.com/michaeldyrynda/laravel-model-uuid/blob/079d354d50f749a7cc371e3e71922246db35a9f6/composer.json#L20-L21

Thank you!

**Comment by michaeldyrynda** [comment]
Laravel 5.6 support is available in 3.1.0!
