### ISSUE TITLE
Default value error on intermediate table of many-to-many relationships.

### ISSUE THREAD

**Issue by akkivaghasiya5** [michaeldyrynda/laravel-model-uuid#42]
I have three eloquent models. i.g, products, categories, and product_category. There is many-to-many relationship between products and categories. Here are table columns of all table.

*products*
id, uuid, name

*categories*
id, uuid, name

*product_category*
id, uuid, product_id, category_id

Here are model clases

    class Product extends Model {
        use GeneratesUuid, SoftDeletes;
    
        protected $uuidVersion = 'ordered';
        protected $dates = ['deleted_at'];
        
       public function getRouteKeyName() {
            return 'uuid';
        }
    
        public function categories() {
            return $this->belongsToMany(Category::class, 'product_category')->using(ProductCategory::class);
        }
    }

    class Category extends Model {
        use GeneratesUuid, SoftDeletes;
    
        protected $uuidVersion = 'ordered';
        protected $dates = ['deleted_at'];
        
       public function getRouteKeyName() {
            return 'uuid';
        }
    
        public function products() {
            return $this->belongsToMany(Product::class, 'product_category')->using(ProductCategory::class);
        }
    }

    class ProductCategory extends Pivot {
        use GeneratesUuid, SoftDeletes;
    
        protected $uuidVersion = 'ordered';
        protected $dates = ['deleted_at'];
        
       public function getRouteKeyName() {
            return 'uuid';
        }
    
        public function tickets() {
            return $this->belongsToMany(Ticket::class);
        }
    }

I have added uuid column in the intermediate table of relationship because I have to use that table as parent record for another relationship too (i.g, tickets) and so I have used Pivot table concept for ProductCategory class.

While I have tried to attach a category to a product, "SQLSTATE[HY000]: General error: 1364 Field 'uuid' doesn't have a default value" error is thrown. I understood the reason. But I don't know how to fix it using GeneratesUuid trait. Either I'm missing something or functionality is not developed in GeneratesUuid.

**Comment by michaeldyrynda** [comment]
The trait relies on Laravel’s model events in order to set the UUID value. I’m not in front of a computer at the moment, but it’s quite possible that the event isn’t fired by the `attch` method, so the trait’s `boot` method will never be called.

**Comment by michaeldyrynda** [comment]
Hey @akkivaghasiya5 - I've just done some testing with this and can confirm that the `creating` event is not fired by the framework when using the `attach` method, so you won't be able to use the `GeneratesUuid` trait on the pivot model in this way.

I'm happy to review a pull request to add the functionality, but I don't have the time available to make this change myself.

**Comment by tobischulz** [comment]
If there is a need for a id on the pivot table, would it be bad-practice if its an incremental integer but the models uses an uuid? Is this an "anti-pattern" or something that you shouldnt do?

I mean, mixed types of ids. 🤔

**Comment by michaeldyrynda** [comment]
I use the integer for all my relationships and the UUID only for public / URL display, which is the [more efficent](https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/) approach to using UUIDs.
