### ISSUE TITLE
Question: Overriding the uuid column name

### ISSUE THREAD

**Issue by daviddiramio** [michaeldyrynda/laravel-model-uuid#43]
Is there a good way to override the 'uuid' column named with say 'id'?

I only want to have an 'id' column with type 'uuid'. I am able to do so by replacing 'uuid' with 'id' throughout GeneratesUuid.php, but obviously that's not the ideal way.

Thanks!

**Comment by michaeldyrynda** [comment]
There isn’t a way to do so at the moment, but changing the trait to use a method instead of hard coded string (similar to how Laravel’s default auth handles `username`) ought to be trivial to implement.

**Comment by daviddiramio** [comment]
Thanks for the quick reply! That would be an awesome feature of your package!

**Comment by michaeldyrynda** [comment]
Just pointing out that the readme does point to [reasons](https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/) why the default, auto-incrementing index remains in place alongside the `uuid` column, so it's a technical decision more than a philosophical one.
