### ISSUE TITLE
Adding to existing project

### ISSUE THREAD

**Issue by retrogradeMT** [michaeldyrynda/laravel-model-uuid#46]
*This is not an issue.  Just a use question* 

I'd like to use this on an existing table.  Will I need to loop through every record to populate the uuid column?

**Comment by michaeldyrynda** [comment]
The package will only set on create, so you’ll need to find your own way to add UUIDs for the existing records

**Comment by HamidReza63** [comment]
Hi, 
I tried this code to populate exsisting customers table
        $customers = Customer::all();
        foreach ($customers as $customer) {
          $customer->uuid = \Ramsey\Uuid\Uuid::uuid4()->getBytes();
          $customer->save;
        }
it doesn't work. it populate all uuids with all 0s. would you please show me the right way .
I installed both pakeges . it is working well on create.
Regards
