### ISSUE TITLE
Relations on uuid Field

### ISSUE THREAD

**Issue by ragingdave** [michaeldyrynda/laravel-model-uuid#49]
In trying to switch between the no longer maintained spatie package and this one, I am finding a very big issue in doing so. Creating a relation based on the binary uuid field will end up failing completely because if the key in the related table is the non-text uuid but instead the binary uuid, then package will convert the uuid to text as a part of the casting and cause the relation to fail completely.

Is there a work around or planned logic to at least enable this?

**Comment by kentdahl** [comment]
+1 as I'm currently not sure how to do this cleanly either. 

The simple cases seem to work if I use the binary UUID value directly creating the related model which has binary UUID as foreign key:

```php
'report_instance_uuid' => $report_instance->getAttributes()['uuid'],
```

The `belongsTo` relationship also seems to work as long as both sides are binary UUIDs.

(With the spatie package I also felt we were missing a trait to use for models that had foreign binary UUIDs but not primary key UUID; I think they had a PR with suggestion for split of functionality for this.)

Any hints and tips appreciated.

**Comment by ragingdave** [comment]
At this point I was lucky enough to be able to just remove this functionality ( being able to related models via the binary uuid), so at this time it's not an issue for me, but still definitely an issue when trying to make the switch

**Comment by logan-jobzmall** [comment]
@michaeldyrynda any news on how or when this will be handled?

**Comment by michaeldyrynda** [comment]
I've no plans to implement this myself, though will accept a PR to introduce this functionality.

I typically use regular incrementing integers for relationship methods and UUID for public / URL lookups only. This is also the [more efficient approach](https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/).

**Comment by vaishnavmhetre** [comment]
I'm using binary uuid and what happened was the relation would get cast (uuid) value than original (binary) value from self table and compare it with original (binary) value on related table.

I found a naive and dirty workaround - 

**User class**

    public function getIdBinaryAttribute(){
        return $this->getOriginal('id');
    }

    public function organisedEvents()
    {
        return $this->hasMany(Event::class, 'user_id', 'id_binary');
    }

**Event class**

    public function getUserIdBinaryAttribute(){
        return $this->getOriginal('user_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id_binary');
    }

This keeps the output unchanged as we didn't append the binary values to appends array but can use it if they want! Unfortunately, this is just a workaround and a more redundant code to be done!

**Comment by schmoove** [comment]
> I'm using binary uuid and what happened was the relation would get cast (uuid) value than original (binary) value from self table and compare it with original (binary) value on related table.
> 
> I found a naive and dirty workaround -
> 
> **User class**
> 
> ```
> public function getIdBinaryAttribute(){
>     return $this->getOriginal('id');
> }
> 
> public function organisedEvents()
> {
>     return $this->hasMany(Event::class, 'user_id', 'id_binary');
> }
> ```
> 
> **Event class**
> 
> ```
> public function getUserIdBinaryAttribute(){
>     return $this->getOriginal('user_id');
> }
> 
> public function creator()
> {
>     return $this->belongsTo(User::class, 'user_id_binary');
> }
> ```
> 
> This keeps the output unchanged as we didn't append the binary values to appends array but can use it if they want! Unfortunately, this is just a workaround and a more redundant code to be done!

@vaishnavmhetre is this solution compatible with Laravel 8? I've found I needed to change `getOriginal()` to `getRawOriginal()` but can't get it to resolve the related collection :(

**Comment by vaishnavmhetre** [comment]
> > I'm using binary uuid and what happened was the relation would get cast (uuid) value than original (binary) value from self table and compare it with original (binary) value on related table.
> > 
> > I found a naive and dirty workaround -
> > 
> > **User class**
> > 
> > ```
> > public function getIdBinaryAttribute(){
> >     return $this->getOriginal('id');
> > }
> > 
> > public function organisedEvents()
> > {
> >     return $this->hasMany(Event::class, 'user_id', 'id_binary');
> > }
> > ```
> > 
> > **Event class**
> > 
> > ```
> > public function getUserIdBinaryAttribute(){
> >     return $this->getOriginal('user_id');
> > }
> > 
> > public function creator()
> > {
> >     return $this->belongsTo(User::class, 'user_id_binary');
> > }
> > ```
> > 
> > This keeps the output unchanged as we didn't append the binary values to appends array but can use it if they want! Unfortunately, this is just a workaround and a more redundant code to be done!
> 
> @vaishnavmhetre is this solution compatible with Laravel 8? I've found I needed to change `getOriginal()` to `getRawOriginal()` but can't get it to resolve the related collection :(

Damn unsure for I left Laravel an year and half ago....

**Comment by Vito0912** [comment]
Is there any update?
"Need" to work with uuids and don´t want to switch. But this is a "no-go" for me.
@schmoove "solution" is a step forward. But i don´t get any results. But the uuid should be parsed correctly.
```
273 Execute	select * from `user` where `user`.`user_id` in ('\›Z\üê‚¶M\‹\ƒ\œ\æ(\±\¡\—') limit 1
		   273 Close stmt	
		   273 Prepare	select * from `role` where `role`.`user_id` in (?)
		   273 Execute	select * from `role` where `role`.`user_id` in ('\›Z\üê‚¶M\‹\ƒ\œ\æ(\±\¡\—')
```

**Comment by michaeldyrynda** [comment]
It is not recommended to us UUID for a primary key, and certainly not binary fields. 

Laravel handles Eloquent primary keys in special ways that evidently take precedence over the package's transformation. 

Should you find a reliable solution to this, feel free to submit a PR for review, but as using UUIDs in this way contradicts the package recommendation, I'm not going to spend time working on a solution for this.

**Comment by schmoove** [comment]
@Vito0912 as @michaeldyrynda suggests, it's best to use an integer primary key for fetching records by ID, and FK relationships. The `uuid` column should only be used for anything public facing.

I started my first project using this library with the wrong approach, and am hoping to revert to the recommended way in due course.

**Comment by Vito0912** [comment]
@schmoove.
Ik a little off-topic, but:
But wouldn´t this result in a lot of joins where they should not be?
Example:
A customer wants to get all Columns from a table called permissions liked to role.

Yet a customer would request it with the uuid ab8-....
With my, apparently bad solution, i just had to select `SELECT * FROM permission WHERE id = 8ba-....`

With the recommened i had to make two querrys every time:
`SELECT role_id FROM role WHERE uuid = 8ba-..`
`SELECT * FROM permission WHERE id = role_id`

Is this right or do I overlook someting?
Also can someone please provide an easy way of doing, if possible, this in laravel without having to use infinte joins?
