### ISSUE TITLE
issue with method 'hasCast' when model extends 'IndexConfigurator' instead 'Model'

### ISSUE THREAD

**Issue by abkrim** [michaeldyrynda/laravel-model-uuid#55]
Hi. 

I use a package `babenkoivan/scout-elasticsearch-driver` for use Laravel Eloquent with ElasticSearch.

This force to extend my class 👍 
```php
use ScoutElastic\IndexConfigurator;
use ScoutElastic\Migratable;
use Dyrynda\Database\Support\GeneratesUuid;


class Advert extends IndexConfigurator
{
    use GeneratesUuid;
    use Migratable;

...
```

But this code get a issue wuth I need implement method `hasCast`

I see in your code

```php
abstract public function hasCast($key, $types = null);
```

But I'm lost about this and what can I do to correct the problem.

**Comment by michaeldyrynda** [comment]
You'll need to implement the `hasCast` method in your model.

It is provided by the framework's `Model` class and is needed for this package to work.
