### ISSUE TITLE
$bytes string should contain 16 characters error fix

### ISSUE THREAD

**Issue by ctf0** [michaeldyrynda/laravel-model-uuid#57]
following the docs along with setting the column to `$table->uuid('id')->primary();` was giving error of `InvalidArgumentException  : $bytes string should contain 16 characters.` so to fix it we need 
```php
public function getIncrementing()
    {
        return false;
    }
```
to be added as well

**Comment by michaeldyrynda** [comment]
This is already documented in the readme. 

> *Note*: this package explicitly does not disable auto-incrementing on your Eloquent models. In terms of database indexing, it is generally more efficient to use auto-incrementing integers for your internal querying. Indexing your uuid column will make lookups against that column fast, without impacting queries between related models.
