### ISSUE TITLE
Error with two uuid fields in the same table

### ISSUE THREAD

**Issue by diegomagikal** [michaeldyrynda/laravel-model-uuid#58]
Hi,

My app has a 'meta values' table with two uuid fields: `uuid` and `parent_uuid`. I put both in the casts attribute like this:

`protected $casts = ['uuid' => 'uuid', 'parent_uuid' => 'uuid']; `

But I get the error "Malformed UTF-8 characters, possibly incorrectly encoded" from `parent_uuid` field.  I examined the `castAttribute `method and I saw that support to two or more uuid fields in the same table does not exists.

There is any way to work around this? Thanks.

**Comment by padre** [comment]
@diegomagikal I have the same issue.  I'm not able to solve it.

**Comment by diegomagikal** [comment]
@padre please check my PR https://github.com/michaeldyrynda/laravel-model-uuid/pull/59

**Comment by michaeldyrynda** [comment]
Will be tagged in 5.0.0
