### ISSUE TITLE
Scope where in

### ISSUE THREAD

**Issue by Maidomax** [michaeldyrynda/laravel-model-uuid#60]
At the moment, the package has a scope `whereUuid`, but does not have a scope `whereUuidIn` where multiple uuid values would be passed. Am I missing something?

**Comment by michaeldyrynda** [comment]
I've never had a need for it, but I'm happy to take a look at a PR that introduces the functionality.

**Comment by Maidomax** [comment]
@michaeldyrynda I'll try to find the time to give it a go in the coming days.

**Comment by michaeldyrynda** [comment]
Closed by aed719e2f3023a39bf3cce5c8cd762fccbf4e9dd
