### ISSUE TITLE
Manually create UUIDs

### ISSUE THREAD

**Issue by francoislevesque** [michaeldyrynda/laravel-model-uuid#67]
For our current project, we need the UUID before pushing in bulk to the database (our models are referencing themselves in a tree-like structure).

We could simply extract the "creating" method in its own method?

```
public static function bootGeneratesUuid(): void
{
        static::creating(function ($model) {
            $model->createUuid();
        });
}

public function createUuid()
{
    $uuid = $model->resolveUuid();
    foreach ($model->uuidColumns() as $item) {
        if (isset($model->attributes[$item]) && ! is_null($model->attributes[$item])) {
            /* @var \Ramsey\Uuid\Uuid $uuid */
                $uuid = $uuid->fromString(strtolower($model->attributes[$item]));
            }
        $model->attributes[$item] = $model->hasCast($item, 'uuid') ? $uuid->getBytes() : $uuid->toString();
    }
}
```

Could it work? 
Thanks!

**Comment by michaeldyrynda** [comment]
The package handles ignoring the `uuid` columns if they already have a value, so if you're pregenerating the UUID, there should be no problem here.

I don't necessarily think it's appropriate for the trait - and by extension the model - to expose how it generates UUIDs as part of the public API.
