### ISSUE TITLE
UUIDv6

### ISSUE THREAD

**Issue by rogatty** [michaeldyrynda/laravel-model-uuid#70]
https://github.com/ramsey/uuid introduced support for UUIDv6 in version [4.0.0-alpha4](https://github.com/ramsey/uuid/blob/master/CHANGELOG.md#400-alpha4---2020-02-23). UUIDv6 achieves the same purpose as Laravel's `Str::orderedUuid()` but in a standardised manner, see http://gh.peabody.io/uuidv6/.

I propose to add `uuid6` to the list of supported versions in the `GeneratesUuid` class. I'm not sure if it's an in-place replacement for `ordered` or if the algorithm is somehow different from `Str::orderedUuid()`.

**Comment by michaeldyrynda** [comment]
We can add support for this once 4.0.0 has been tagged stable 👍

**Comment by michaeldyrynda** [comment]
Resolved by #83

**Comment by rogatty** [comment]
@michaeldyrynda I believe https://github.com/michaeldyrynda/laravel-model-uuid/blob/master/src/GeneratesUuid.php needs to be updated before this can be resolved.

**Comment by rogatty** [comment]
Thanks!
