### ISSUE TITLE
Composer needs update

### ISSUE THREAD

**Issue by webfacer** [michaeldyrynda/laravel-model-uuid#79]
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

**Comment by michaeldyrynda** [comment]
We will as soon as `ramsey/uuid` tags 4.0.0.

**Comment by caiquecastro** [comment]
Version updated on: https://github.com/michaeldyrynda/laravel-model-uuid/pull/83

**Comment by michaeldyrynda** [comment]
Resolved by #83
