### ISSUE TITLE
Readme: move installation section at the top

### ISSUE THREAD

**Issue by webfacer** [michaeldyrynda/laravel-model-uuid#80]
I would suggest to set the Installation doc section at the top, so we can find it faster if we wanne install it. Would be great.

thx

**Comment by michaeldyrynda** [comment]
I'm happy leaving it how it is for now. Prefer the explanatory stuff at the top, with the installation instructions later, once you understand what you're getting yourself in for.

https://m.dotdev.co/how-to-write-a-readme-that-rocks-bc29f279611a
