### ISSUE TITLE
no WhereUuid available in this trait

### ISSUE THREAD

**Issue by jcherrabi** [michaeldyrynda/laravel-model-uuid#85]
Hello there,
i'm not sure if i'm missing something but I do not see WhereUuid method in this trait as suggested in the example on th ereadme `// Find a specific post with the default (uuid) column name
$post = Post::whereUuid($uuid)->first();
`
even looking at the source I only see scopeWhereUuid() so have I miss understood something?

**Comment by davidhemphill** [comment]
The `whereUuid` method is known as a "Dynamic Where Clause" inside of Laravel: https://laravel.com/docs/5.0/queries. It's essentially a magic method that assumes `uuid` is a column on your database table. You can do this with any column actually, `whereId`, `whereCreatedAt`, etc

**Comment by devcircus** [comment]
That's how scopes work.

**Comment by jcherrabi** [comment]
Thanks, and yes, I just got relient so on the intellisense that I was waiting for it to bring it up while typing LOL... maybe I need to adjust something so intellisense can make sense of it...

thank you it works as written and sorry for the misunderstanding .. ;)

**Comment by andrewmclagan** [comment]
There should be a docbloc so this is recognised

**Comment by michaeldyrynda** [comment]
Happy to review a PR!

**Comment by ninjaparade** [comment]
I'd review that PR as well.

**Comment by ninjaparade** [comment]
@andrewmclagan ping me when its ready to review.

**Comment by andrewmclagan** [comment]
take a look next week under the pump at the moment :-)

**Comment by ninjaparade** [comment]
Not sure what you’re doing under the pump? Seems rather odd place to be.

**Comment by JeroenVanOort** [comment]
It's probably this that would need to be added:

```
/**
 * @method static Builder whereUuid(string $uuid)
 */
```

Don't have the time to make a PR now, but came accross an internal PR where a developer added this on application level.

**Comment by michaeldyrynda** [comment]
Pushed the docblock change. Thanks all!

**Comment by andrewmclagan** [comment]
@michaeldyrynda great thanks!

@ninjaparade hahaha its an Australian term for "Very busy" never really thought about it deeply... 

https://dictionary.cambridge.org/dictionary/english/under-the-pump

**Comment by ninjaparade** [comment]
![image](https://user-images.githubusercontent.com/228899/92072178-79d98600-ed65-11ea-92b3-9eb812aa954c.jpeg)
