### ISSUE TITLE
Uuid can be re-set after creation.

### ISSUE THREAD

**Issue by defenestrator** [michaeldyrynda/laravel-model-uuid#86]
I am using both this and efficient-uuid packages, and did this test in tinker. This could cause some pretty nasty issues with distributing data across different persistence systems, for instance.

![Screen Shot 2020-04-01 at 15 28 22](https://user-images.githubusercontent.com/529446/78188431-709e6300-742d-11ea-8b5b-8ef38d0832dd.png)

Would a PR with something like the below be adequate? I can throw some tests on it, as well.

```php
// Just a little extra protection against `dah l33t h4x` and dumb accidents.
        static::saving(function ($model) {
            $model->id = $model->getOriginal('uuid');
        });
```
Thanks, and cheers!

**Comment by michaeldyrynda** [comment]
I don't want this package to be responsible for preventing you from overriding a UUID if it's set. That's something you can control within your own application.
