### ISSUE TITLE
Query Builder!

### ISSUE THREAD

**Issue by boranbar** [michaeldyrynda/laravel-model-uuid#92]
Hello,

I'm using this package with https://github.com/michaeldyrynda/laravel-efficient-uuid

So, in the docs you say:

// Find a specific post with the default (uuid) column name
`$post = Post::whereUuid($uuid)->first();`

If i want to retrieve a data with `DB::table` it returns null.

For storing data or retrieve data, is there a way to use with `DB Facade` also?

**Comment by michaeldyrynda** [comment]
There is no integration with the query builder, as this package is built to support UUID with Eloquent. I would consider a PR to add the functionality to the package.
