### ISSUE TITLE
Error caused by the latest version of Ramsey/UUID

### ISSUE THREAD

**Issue by aaronflorey** [michaeldyrynda/laravel-model-uuid#93]
`Return value of Modal::resolveUuid() must be an instance of Ramsey\Uuid\Uuid, instance of Ramsey\Uuid\Lazy\LazyUuidFromString returned`

Downgrading from `4.1` to `4.0.1` got it working again. I don't have time to dig into the issue right now, but if i do, i'll find the issue and submit a PR.

**Comment by michaeldyrynda** [comment]
Fixed in b273499c41f62a8601a385f1652ba5ee584b0a5f. Note that you must now use either UUID version 1, 4, or 6.
